make it `nix build` -able
for whatever reason, GHC 9.4.4 was erroring with something seemingly
about `text` version bounds:

```
Configuring string-qq-0.0.4...
CallStack (from HasCallStack):
  withMetadata, called at libraries/Cabal/Cabal/src/Distribution/Simple/Utils.hs:370:14 in Cabal-3.8.1.0:Distribution.Simple.Utils
Error: Setup: Encountered missing or private dependencies:
text >=1.2 && <1.3
```

I figured it might be about new versioned Haskell pkgs not yet in nixpkgs,
so I regressed to GHC 9.2.5, and that works.